### ISSUE TITLE
Uploading release assets in parallel results in TaskCanceledException

### ISSUE THREAD

**Issue by eiriktsarpalis** [octokit/octokit.net#963]
I'm maintaining a project which requires a large number of files to be uploaded with each release. Roughly 30 files of 8MB each. My current build script uploads the files in sequence, which can take an annoying amount of time. I've been investigating whether I could use octokit to upload assets in parallel, but this has resulted in the upload tasks returning random TaskCanceledExceptions. Reproduction is simple really, in F#

``` fsharp
let client : GitHubClient = ...
let draftRelease : Release = ...
let uploadFile (fileName : string) : Task<ReleaseAsset> =
    let fi = FileInfo(fileName)
    let fs= File.OpenRead(fi.FullName)
    let assetUpload = new ReleaseAssetUpload(fi.Name,"application/octet-stream",fs,Nullable<TimeSpan>())
    client.Release.UploadAsset(draftRelease, assetUpload)

let globalTask = files |> Array.map uploadFile |> Task.WhenAll
globalTask.Result
```

**Comment by naveensrinivasan** [comment]
The reason for the `TaskCanceledExceptions` is because the  default [HttpClient] (https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.100).aspx) `Timeout` is 100 seconds. 

I tried changing in the sample from `Nullable<TimeSpan>()`  to `new TimeSpan(0, 10, 0)` to see if that would fix. But the [HttpClientAdapter] (https://github.com/octokit/octokit.net/blob/f0111aa72239da06c6268ae0c47562957f6603bc/Octokit/Http/HttpClientAdapter.cs) that is implemented does not set the timeout passed in the request to the `HttpClient`. The `Timeout` is being used only used in the `CancellationTokenSource` https://github.com/octokit/octokit.net/blob/f0111aa72239da06c6268ae0c47562957f6603bc/Octokit/Http/HttpClientAdapter.cs#L53-65

This is a bug. The `Timeout` property should set to the `TimeSpan` set in the Request. 

I'll do a PR for this. 

By the time if you want a workaround you could have a `HttpClient` class that implements `IHttpClient` and pass that to the `Connection` class like this.

```csharp
	var client = new Connection(new Octokit.ProductHeaderValue("uploadrelease"),new YourOwnHttpClient())
```

**Comment by eiriktsarpalis** [comment]
Do you have any updates on this fix? Thanks.

**Comment by shiftkey** [comment]
@eiriktsarpalis we already have an override for the timeout when uploading a release asset. Apologies for not mentioning it earlier:

```fsharp
...
let assetUpload = new ReleaseAssetUpload(fi.Name,"application/octet-stream",fs, Nullable (TimeSpan.FromMinutes(5.0)))
```

Can you confirm this addresses the issue?

**Comment by naveensrinivasan** [comment]
@shiftkey If I am not wrong the timeout is only for that request which is cancellation token. But http would time out all the request when it reaches 100 seconds https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.100).aspx . @eiriktsarpalis  is using the same http client with multiple simultaneous concurrent requests.

**Comment by shiftkey** [comment]
I must confess that it's been a while since this was last raised https://github.com/octokit/octokit.net/issues/567 - and given how people seem to be care when this gets in the way I'm going to look at whether it's possible to just remove this limitation. How does that feel @eiriktsarpalis @naveensrinivasan? 

I'll follow up in #965 about the global change for timeout, because there's other tangential stuff to talk about there.

**Comment by pmiossec** [comment]
I am confronted to this bug :( It is still there in the new 0.23 release.
It make the upload of release asset feature completly useless...
Do you think if the this bug will be fixed ?

I could perhaps take some time to do a PR but how do you want to fix it?
1. Set a huge Timeout on the HttpClient
2. Expose a Timeout property
3. (Potentialy) Update the Timeout at each request depending of the request timeout?

**Comment by pmiossec** [comment]
Is this bug be fixed?
I can't find it in the release not or in the issues or PR linked.
Seems not :(
Could it be fixed by at least rising the timeout?

**Comment by ryangribble** [comment]
Hi @pmiossec 

Given its still open I don't believe it would be fixed. 

You mentioned in git-tfs project that you built a custom version of octokit with this fixed... If you'd like to send a PR with the fix I'll work with you to get it merged 👍

**Comment by mikasoukhov** [comment]
The problem still exist

client.SetRequestTimeout(TimeSpan.FromMinutes(30));

Version 0.29.0.0

**Comment by ryangribble** [comment]
Hi @mikasoukhov can you provide more details?  

- a complete code sample showing the octokit call?  
- indication on how large your release asset is?
- at what point do you get the exception?

thanks

**Comment by mikasoukhov** [comment]
Unfortunately, I cannot provide the full code.

The upload fails on following lines (file size is about 200mb)

```
var client = new GitHubClient(new ProductHeaderValue(repo))
			{
				Credentials = new Credentials("51ee1202fb27b87a7f72875adcf0b463d3c2a9b2")
			};

			client.SetRequestTimeout(TimeSpan.FromMinutes(30)); // timeout looks like about 1-2 min, not 30 min at all.

.....

using (var archiveContents = File.Open(attach, System.IO.FileMode.Open))
			{
				var assetUpload = new ReleaseAssetUpload
				{
					FileName = Path.GetFileName(attach),
					ContentType = "application/zip",
					RawData = archiveContents,
				};

				client.Repository.Release.UploadAsset(release, assetUpload).Wait(); // <-- exception
			}
```

**Comment by ryangribble** [comment]
Sorry, by full sample I meant "relevant" code, so what you've posted is fine :+1:

Can you try setting the `TimeOut` property on `ReleaseAssetUpload` request object as well?  

``` csharp
var assetUpload = new ReleaseAssetUpload
{
    FileName = Path.GetFileName(attach),
    ContentType = "application/zip",
    RawData = archiveContents,
    TimeOut = TimeSpan.FromMinutes(30)
};
```
